export const english = {
  general: {
    changeLanguage: "Change Language to GERMAN",
    teamName: "CSS DISASTER",
    warning: "WARNING",
    error: "ERROR",
    info: "INFO",
    debug: "DEBUG",
    reloadPage: "You have to reload the page to change the language!",
  },

  tasks: {
    "drag-and-drop-task": "Drag & Drop Task",
    "fill-shape-task": "Fill Shapes Task",
    "gesture-recognition-task": "Gesture Recognition Task",
    "morse-code-task": "Morse Code Task",
    "resize-screen-task": "Resize Screen Task",
    "timing-task": "Timing Task",
    "reaction-task": "Reaction Task",
    "geo-distance-task": "Geo Distance Task",
  },

  welcome_start: {
    title: "WELCOME TO APIRUSH",
    subTitle: "THE BEST GAME EVER",
    userName: "Define your username",

    enterGame: "ENTER EXISTING GAME",
    createGame: "CREATE NEW GAME",
    showStats: "SHOW STATS",
    showAllTasks: "SHOW ALL TASKS",

    noUserName: "You didn't include a username, we don't want to hide the name of the winner!",
  },

  welcome_join: {
    title: "CHOOSE A GAME TO JOIN",
  },
  welcome_create: {
    title: "CREATE HERE A NEW GAME",
    gameName: "CHOOSE NAME",
    gameNameHint: "ENTER THE GAME NAME",
    createGame: "CREATE GAME",
    noGameName: "You have not entered a game name!",
  },
  pre_game: {
    title: "OTHER PLAYERS ARE JOINING",
    startGame: "START NOW",
  },
  in_game: {
    startTask: "Press SPACE to start the task!",
    enabled: "enabled",
    disabled: "disabled",
    animations: "Animations",
    debug: "Debug mode",
    help: "Welcome to APIRush.\nPress W-A-S-D to move around the board.\nInteract with tasks by using SPACE.",
    playAgain: "Press SPACE to play again!",
    joined: "joined the game!",
    left: "left the game!",
    winner: "WINNER",
  },
  welcome_stats: {
    title: "STATS SCREEN",
    totalTime: "TOTAL PLAYING TIME",
  },
  welcome_all_tasks: {
    title: "ALL TASKS",
  },

  gesture_recognition_task: {
    pleaseWait: "Please wait ...",
  },
  fill_shape_task: {
    error_msg_many_times_outside: "Woops, too many times colored outside.",
    error_msg_many_px_outside: "Woops, too many  pixels colored outside",
    fill_msg: "Fill",
    percentage_check_win_msg: "You did it!!! ",
    percentage_check_fail_msg: "Nope. Nice Try. ",
  },
  morse_code_task: {
    error_msg_signal_incomplete: "Signal incomplete. (<80%)",
    msg_signal_complete: "Accuracy: ",
  },
  resize_screen_task: {
    current_size_msg: "Current size:",
    resize_to_msg: "Resize to:",
    check_win_msg: "You did it!!! ",
    check_fail_msg: "Nope. Nice Try. ",
  },
  drag_and_drop_task: {
    check_win_msg: "You did it!!! ",
    check_fail_msg: "Nope. Wrong File. ",
    task_msg_1: "Drag and Drop file ",
    task_msg_2: " from folder 'Downloads'",
  },
  geo_distance_task: {
    you_are: "You are ",
    km_off: "km off. Try again!",
    task_complete: "Task complete! Distance: ",
    geo_permission_denied: "Geolocation request denied.",
    geo_position_unavailable: "Location information unavailable.",
    geo_timeout: "Location request timed out.",
    geo_unknown: "Unknown error.",
    locations: {
      airport: "Airport, Graz",
      main_square: "Main Square, Graz",
      clock_tower: "Clock Tower, Graz",
      old_campus: "TU Graz, Old Campus, Graz",
      inffeld: "TU Graz, Inffeldgasse, Graz",
    },
    geo_title: "Guess the distance!",
    geo_desc: "Distance between your current location and:",
    hint: "Guess the distance in kilometers",
  },
  timer_tasks: {
    not_started: "Timer has not started yet. Try again!",
    your_reaction: "Your reaction",
    success: "Success!",
    you_were: "You were",
    too_slow: "seconds too slow! Try again!",
    reaction_info: "Press the button immediately after the box turns green!",
    timer_info: "Press the button {0} seconds after the box turns green!",
    target_time: "Target time",
    your_time: "Your time",
    seconds_too_slow: "seconds too slow",
    seconds_too_fast: "seconds too fast",
    try_again: "Try again!",
  },
};
export const german = {
  general: {
    changeLanguage: "Sprache ändern zu ENGLISCH",
    teamName: "CSS KATASTROPHE",
    warning: "WARNUNG",
    error: "FEHLER",
    info: "INFO",
    debug: "DEBUG",
    reloadPage: "Sie müssen die Seite neu laden um die Sprache zu ändern!",
  },
  tasks: {
    "drag-and-drop-task": "DragAndDropTask",
    "fill-shape-task": "FillShapeTask",
    "gesture-recognition-task": "GestureRecognitionTask",
    "morse-code-task": "MorseCodeTask",
    "resize-screen-task": "ResizeScreenTask",
    "timing-task": "TimingTask",
    "reaction-task": "ReactionTask",
    "geo-distance-task": "Geo Distance Task",
  },

  welcome_start: {
    title: "WILLKOMMEN BEI APIRUSH",
    subTitle: "DAS BESTE SPIEL ALLER ZEITEN",
    userName: "IHREN BENUTZERNAMEN EINGEBEN",

    enterGame: "BESTEHENDES SPIEL BEITRETEN",
    createGame: "NEUES SPIEL ERSTELLEN",
    showStats: "STATISTIK ANZEIGEN",
    showAllTasks: "ALLE AUFGABEN ANZEIGEN",

    noUserName: "Sie haben keinen Benutzernamen angegeben, wir wollen den Namen des Gewinners nicht verstecken!",
  },

  welcome_join: {
    title: "WÄHLEN SIE EIN SPIEL, DEM SIE BEITRETEN MÖCHTEN",
  },
  welcome_create: {
    title: "ERSTELLEN SIE HIER EIN NEUES SPIEL",
    gameName: "NAMEN WÄHLEN",
    gameNameHint: "EINGABE DES SPIELNAMENS",
    createGame: "SPIEL ERZEUGEN",
    noGameName: "Sie haben keinen Spielnamen eingegeben!",
  },
  pre_game: {
    title: "ANDERE SPIELER SIND DABEI",
    startGame: "JETZT STARTEN",
  },
  in_game: {
    startTask: "Drücken Sie die LEERTASTE, um den Task zu starten!",
    enabled: "aktiviert",
    disabled: "deaktiviert",
    animations: "Animationen",
    debug: "Debug Modus",
    help:
      "Willkommen bei APIRush.\nDrücken Sie W-A-S-D um sich über das Spielfeld zu bewegen.\nBenutzen Sie die LEERTASTE, um mit Aufgaben zu interagieren.",
    playAgain: "Drücken Sie die LEERTASTE um erneut zu spielen",
    joined: "ist dem Spiel beigetreten!",
    left: "hat das Spiel verlassen!",
    winner: "SIEGER",
  },
  welcome_stats: {
    title: "STATISTIKBILDSCHIRM",
  },
  welcome_all_tasks: {
    title: "ALLE AUFGABEN",
  },

  gesture_recognition_task: {
    pleaseWait: "Bitte warten ...",
  },
  fill_shape_task: {
    error_msg_many_times_outside: "Uups, zu oft rausgemahlt.",
    error_msg_many_px_outside: "Uups, zu viele falsche Pixel ausgemahlt.",
    fill_msg: "Fülle",
    percentage_check_win_msg: "Du hast es geschafft!!! ",
    percentage_check_fail_msg: "Nein. Netter Versuch. ",
  },
  morse_code_task: {
    error_msg_signal_incomplete: "Signal unvollständig. (<80%)",
    msg_signal_complete: "Genauigkeit: ",
  },
  resize_screen_task: {
    current_size_msg: "Aktuelle Göße",
    resize_to_msg: "Zielgröße:",
    check_win_msg: "Du hast es geschafft!!! ",
    check_fail_msg: "Nein. Netter Versuch. ",
  },
  drag_and_drop_task: {
    check_win_msg: "Du hast es geschafft!!! ",
    check_fail_msg: "Nein. Falsche Datei. ",
    task_msg_1: "Drag and Drop Datei ",
    task_msg_2: " vom Ordner 'Downloads'",
  },
  geo_distance_task: {
    you_are: "Sie liegen ",
    km_off: "km daneben. Versuchen Sie es erneut!",
    task_complete: "Task abgeschlossen! Distanz: ",
    geo_permission_denied: "Geolocation Anfrage abgelehnt.",
    geo_position_unavailable: "Position nicht verfügbar.",
    geo_timeout: "Zeitüberschreitung bei der Positionsabfrage",
    geo_unknown: "Unbekannter Fehler.",
    locations: {
      airport: "Flughafen, Graz",
      main_square: "Hauptplatz, Graz",
      clock_tower: "Uhrturm, Graz",
      old_campus: "TU Graz, Alte Technik, Graz",
      inffeld: "TU Graz, Inffeldgasse, Graz",
    },
    geo_title: "Schätzen Sie die Entfernung!",
    geo_desc: "Entfernung von Ihrem aktuellen Standort und:",
    hint: "Schätzen Sie die Distanz in Kilometer",
  },
  timer_tasks: {
    not_started: "Der Timer wurde noch nicht gestartet! Versuchen Sie es erneut!",
    your_reaction: "Ihre Reaktionszeit",
    success: "Erfolgreich!",
    you_were: "Sie waren",
    too_slow: "Sekunden zu langsam. Versuchen Sie es erneut!",
    reaction_info: "Drücken Sie auf den Button, sobald die Box grün wird!",
    timer_info: "Drücken Sie den Button {0} Sekunden nachdem die Box grün wurde!",
    target_time: "Zielzeit",
    your_time: "Ihre Zeit",
    seconds_too_slow: "Sekunden zu langsam",
    seconds_too_fast: "Sekunden zu schnell",
    try_again: "Versuchen Sie es erneut!",
  },
};
